### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by izumin5210** [srvc/glx#1]

**Comment by izumin5210** [comment]
## Configuration

```yml
# glx.services.yaml

<: &api-gateway-local
  name: api-gateway
  hostname: api.example.local
  path: github.com/example/api-gateway
  port_env:
  - APP_PORT=80
  processes:
  - name: server
    run: ["go", "run", "./cmd/server"]

<: &shopping-cart-docker
  name: shopping-cart
  hostname: shopping-cart.example.local
  path: github.com/example/shopping-cart
  port_envs:
  - PORT=80
  on_start:
  - copy_ssh
  - run: ["bundle", "-j4"]
  processes:
  - name: server
    run: ["bin/rails", "s"]
  - name: sidekiq
    run: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml", "--verbose"]
    adhoc: true
  docker:
    build:
      target: runnable
    volumes:
    - .:/app
    - bundle:/usr/local/bundle
    - tmp:/app/tmp
    - log:/app/log

<: &accounts-k8s
  name: accounts
  hostname: accounts.example.local
  path: github.com/example/accounts
  kubernetes:
    context:   k8s.example.com
    namespace: accounts
    labels:
      role: api
    ports:
      80: 8080
```

```yml
# glx.yaml

root: /Users/izumin/src

projects:
- name: shopping
  apps:
  - *api-gateway-local
  - *shopping-cart-docker
  - *accounts-k8s
```
